### ISSUE TITLE
`We could not find any data` without any verbose error message

### ISSUE THREAD

**Issue by shojibur** [Jagdish-J-P/fpx-payment#1]
HI @Jagdish-J-P 
Thanks for great package, was trying to to implement in another client project, but unfortunately we always get 
`We could not find any data` error, seems it not really showing us what  goes wrong except just giving us that error. Maybe it would be more helpful if provide more verbose error at least during UAT. 

Do you have any advice

Thanks

**Comment by Jagdish-J-P** [comment]
Have you generated Certificate for UAT?

**Comment by Jagdish-J-P** [comment]
Which certificate are you using to generate checksum?

**Comment by Jagdish-J-P** [comment]
This error is sent by FPX server if UAT or Production certificate is invalid.
