### ISSUE TITLE
Page Expired when receiving respond from FPX

### ISSUE THREAD

**Issue by nazirulfitrifauzi** [Jagdish-J-P/fpx-payment#12]
Hi,

I encounter error 419 when receiving post data responded from FPX. Does it caused by the CSRF token?

Furthermore, when I try check the payment status, all I get is _"Failed to verify the request origin"_. Do you mind to give me a few pointer to solve this.

Thanks

**Comment by Jagdish-J-P** [comment]
1. You need to ignore CSRF for your routes.
2. checksum is not matching. Please check the certificate.

**Comment by nazirulfitrifauzi** [comment]
No 1 - done.
No 2 - still failed. I already using the one that you provide in the uat certificate folder, failed. I used the cert that has been given from FPX team, failed. Used the one from FPX website, also failed.

**Comment by nazirulfitrifauzi** [comment]
I have recheck the cert and manage to get it working but still I got the failed status.

I have verify sign the cert and it return true;
![image](https://user-images.githubusercontent.com/55203232/181167967-672cea92-dfb8-46cb-b020-fcf05a87c98b.png)

![image](https://user-images.githubusercontent.com/55203232/181168209-7c7975f9-55f8-4b0a-9f03-cbc146faa699.png)


and manage to get the Post data from the callback, and the status still failed:
![image](https://user-images.githubusercontent.com/55203232/181168149-b0ac5e35-3c8d-4216-89ba-5db841f62ab6.png)

**Comment by Jagdish-J-P** [comment]
Can you please raise support ticket on FPX team. They might be blocking request. You need to whitelist your server to get response, I guess so.

**Comment by Jagdish-J-P** [comment]
Is this resolved?
