### ISSUE TITLE
Need more explanation

### ISSUE THREAD

**Issue by bruosama** [Jagdish-J-P/fpx-payment#16]
I don't really understand what's the first thing to do.

This is what i have done:
composer create-project laravel/laravel laravel-fpx --prefer-dist
composer require jagdish-j-p/fpx-payment
php artisan fpx:publish

copy 3 files from migrations folder
setup .env (create database)

php artisan migrate

copy public, resources and routes

where is app folder?
then i found it in src (but a lot of folders didn't match with local app)

Do i need config/config.php because i already published config/fpx.php above

Now i stuck here...
Please guide me.

**Comment by Jagdish-J-P** [comment]
Why you are looking for app folder inside package? you do not have to copy anything manually. You just have to execute below commands.

composer require jagdish-j-p/fpx-payment
php artisan fpx:publish

Then add below lines in your .env file


FPX_INDIRECT_PATH=payments/fpx/callback
FPX_DIRECT_PATH=payments/fpx/webhook
FPX_INDIRECT_URL="${APP_URL}/${FPX_INDIRECT_PATH}"
FPX_DIRECT_URL="${APP_URL}/${FPX_DIRECT_PATH}"

FPX_EXCHANGE_ID=<add your exchange id here>
FPX_SELLER_ID=<add your seller id here>

then execute below commands
php artisan optimize
php artisan migrate

**Comment by bruosama** [comment]
Yes, figured it out. Huhu. This is package's style. Thank you.

**Comment by fadlisaad** [comment]
`php artisan optimize` this is the magic command that I've missed. Maybe you can add into the documentation
