### ISSUE TITLE
Allow multiple Exchange and Seller ID

### ISSUE THREAD

**Issue by fadlisaad** [Jagdish-J-P/fpx-payment#21]
I've worked with a customer that have multiple FPX exchange (each for B2C and B2B1) so definitely they will have multiple seller ID as well. I think it's time to allow multiple exchange and seller ID to be manage independently, either through a dashboard or just locate the correct exchange certificate in the storage.

I'm working with this and once successfully implement it, if it suit this I will create a pull request.

I'm looking forward for any suggestion or idea, since we are working in a niche field here.

**Comment by Jagdish-J-P** [comment]
I think this can be managed by application itself without making any changes to the package. But you can try and make sure it does not break existing flow.
