### ISSUE TITLE
Callback and webhook not working

### ISSUE THREAD

**Issue by MuhammadSyahmi98** [Jagdish-J-P/fpx-payment#22]
Upon successfully making the payment, I am wondering why the FPX is not redirecting to the callback and there is no webhook response received but display as image below. The Paynet documentation does not provide any guidelines regarding the redirect URL or webhook. Thank you.

![image](https://github.com/Jagdish-J-P/fpx-payment/assets/68889896/2acf2e8b-f933-4523-a33d-4b85f4e87fb2)

**Comment by Jagdish-J-P** [comment]
Webhook will call on production server only. But callback is receiving as it wont print this page if callback is not received.

**Comment by MuhammadSyahmi98** [comment]
1. I apologize for the delayed response. If the callback is being received, but why it's not redirecting back to my system.
2. Is the URL for the webhook and callback predetermined during merchant registration because I do not get have fully access to the API by my client.

**Comment by Jagdish-J-P** [comment]
You can find API documentation at https://fpxexchange.paynet.my/

**Comment by Jagdish-J-P** [comment]
Can you please share below env values?

APP_URL=
FPX_INDIRECT_PATH=
FPX_DIRECT_PATH=
FPX_INDIRECT_URL=
FPX_DIRECT_URL=
