### ISSUE TITLE
InvalidCertificateException

### ISSUE THREAD

**Issue by zarulizham** [Jagdish-J-P/fpx-payment#3]
Hi, when trying to get bank list, I'm getting `InvalidCertificateException` if `FPX_VERIFY_RESPONSE` was true.

Is it normal when using UAT cert?

**Comment by Jagdish-J-P** [comment]
Which certificate are you using??

**Comment by zarulizham** [comment]
UAT certificate (not the ones in documentation).

1. Private: Generated by me (EX00000XXX.key)
2. Public: Received from Paynet. (EX00000XXX.cer)

**Comment by Jagdish-J-P** [comment]
You should use UAT certificate received in documentation as paynet calculates checksum using that certificate.

**Comment by zarulizham** [comment]
I did not found any .cer in the documentation attachment (only fpxuat.crt and EX00001179.key).

__
Initially, I generate private key (EX00000XXX.key) along with .csr (EX00000XXX.csr).

The .csr was emailed to Certificate Management (CM). After a few days, CM replied me with .cer (EX00000XXX.cer).

Am I using the right cert? 

<img width="244" alt="Screenshot 2022-01-30 at 12 06 29 AM" src="https://user-images.githubusercontent.com/10229855/151668072-f9c3a0ab-4001-4d87-a134-af49875dfe7d.png">

**Comment by Jagdish-J-P** [comment]
You are using right certs but in UAT environment FPX is not using this certificate. They are using certificate attached in documentation i.e. fpxuat.crt.

**Comment by zarulizham** [comment]
When I use and download cert from FPX Certificate – UAT (https://exchange.fpx.prod.inet.paynet.my) and @Jagdish-J-P  certificate, the response can be verified now.

**Comment by Jagdish-J-P** [comment]
Have you received Production certificate?

**Comment by zarulizham** [comment]
Not yet. Still undergo some developments. Keep you updated once get them.
