### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by hakimzulkufli** [Jagdish-J-P/fpx-payment#9]
Hi,

Currently this package only supports up to Laravel 8.x. Is there any particular reason why Laravel 9 is not supported?

**Comment by Jagdish-J-P** [comment]
We have currently not tested it on Laravel 9. Hence it is not supported. We are open for collaboration. You can submit pull request for the same.

**Comment by Jagdish-J-P** [comment]
Are you using this package?

**Comment by hakimzulkufli** [comment]
@Jagdish-J-P I am planning to, yes. I am waiting for PayNet to accept our CSR before I can perform any testing with Laravel 9.

**Comment by Jagdish-J-P** [comment]
Laravel 9 is supporting now.
